# Generated by Django 3.0.5 on 2020-04-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200421_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('user', 'publications')},
        ),
    ]
