# Generated by Django 3.0.5 on 2020-04-29 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200423_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='last_updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
